# Generated by Django 3.0.4 on 2020-03-22 10:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='Dollars', max_length=12)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_debited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sources', to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payment.Source')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_type_source', to='payment.SourceType'),
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(max_length=32)),
                ('expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankcards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
