# Generated by Django 3.0.4 on 2020-03-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20200320_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_options',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='option_group',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='options',
        ),
        migrations.DeleteModel(
            name='AttributeOptionGroup',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
