# Generated by Django 3.0.4 on 2020-03-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20200322_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Product Attribute', 'verbose_name_plural': 'Product Attributes'},
        ),
        migrations.AlterModelOptions(
            name='productclass',
            options={'verbose_name': 'Product Class', 'verbose_name_plural': 'Product Classes'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productclass',
            name='slug',
            field=models.SlugField(default='null', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
