# Generated by Django 3.0.4 on 2020-03-20 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Mr,Miss,Mrs,Dr', max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, help_text='First name', max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Last name', max_length=128, null=True)),
                ('line1', models.CharField(help_text='Adress of line1', max_length=128)),
                ('line2', models.CharField(blank=True, help_text='Adress of line2', max_length=128, null=True)),
                ('line3', models.CharField(blank=True, help_text='Adress of line3', max_length=128, null=True)),
                ('city', models.CharField(help_text='City name', max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('zipcode', models.IntegerField()),
                ('search_text', models.CharField(blank=True, help_text='search text for address', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Addresse',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('is_3166_1_a2', models.CharField(help_text='alpha2 code', max_length=2, primary_key=True, serialize=False)),
                ('is_3166_1_a3', models.CharField(blank=True, help_text='alpha3 code', max_length=3)),
                ('is_3166_1_numeric', models.CharField(blank=True, help_text='Numeric code', max_length=3)),
                ('printable_name', models.CharField(help_text='Common name', max_length=128)),
                ('name', models.CharField(help_text='Official name', max_length=128)),
                ('is_shipping_country', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Countrie',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default_shipping', models.BooleanField(default=True)),
                ('is_default_billing', models.BooleanField(default=True)),
                ('total_orders_from_address', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address_super', to='address.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Addresse',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.Country', verbose_name='country'),
        ),
    ]
